apiVersion: v1
kind: Service
metadata:
  name: matcha-scout-api
  namespace: matcha-scout-local
  labels:
    app.kubernetes.io/name: matcha-scout-api
    app.kubernetes.io/part-of: matcha-scout
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matcha-scout-api
  ports:
    - name: http
      port: 8000
      targetPort: http
